cbits/support.cpp.LLVMCreateStandardFunctionPasses: use static_cast instead of dynamic_cast
otherwise we get the linker error
xTvDQ.a(support.o): In function `LLVMCreateStandardFunctionPasses':
(.text+0x26): undefined reference to `typeinfo for llvm::PassManagerBase'
/home/thielema/.cabal/lib/x86_64-linux-ghc-7.4.2/llvm-ffi-3.2.0-1qaIks02vWMLqFV3TxTvDQ/libHSllvm-ffi-3.2.0-1qaIks02vWMLqFV3TxTvDQ.a(support.o): In function `LLVMCreateStandardFunctionPasses':
(.text+0x2d): undefined reference to `typeinfo for llvm::FunctionPassManager'